### ISSUE TITLE
extCtx is null

### ISSUE THREAD

**Issue by aburafia** [freshplanet/ANE-Push-Notification#10]
i got files from master blanch.

i only change 
- build.config
- xcode's FlashRuntimeExtensions.h path

after ,i did ant. ant says BUILD SUCCESSFUL.
after, i publish AIR for Android. Flash says SUCCESS.
but it didnt start. in debug mode log, "extCtx is null".
## what should i do?

my environment is 
osx 01.8.2
java version "1.6.0_37"
xcode Version 4.5.2

---

build.config
name = AirPushNotification
flex.sdk = /Applications/Adobe Flash Builder 4.7/sdks/4.6.0
bin.ext =
ios.sdkversion = iphoneos6.0

**Comment by zing1911** [comment]
@arnovanoordt Which file is added "<extensionID>com.freshplanet.AirPushNotification</extensionID>" ?

**Comment by arnovanoordt** [comment]
It should be added to the Application Descriptor File (manifest) like this:
  <extensions>
    <extensionID>eu.alebianco.air.extensions.analytics.NativeGATracker</extensionID>
  </extensions>
