### ISSUE TITLE
Error: No resource found

### ISSUE THREAD

**Issue by davidabrown** [freshplanet/ANE-Push-Notification#22]
I am trying to compile an app in Flash Builder, AIR 3.7 but before the compile completes I receive the following error:

aapt tool failed:/private/var/folders/9c/_g8fcpxs15q6tp63vms4nkgr0000gn/T/344e7f4c-65d9-4df6-8722-16ba7baa43de/res/layout/com_facebook_usersettingsfragment.xml:48: error: Error: No resource found that matches the given name (at 'style' with value '@style/com_facebook_loginview_silver_style').

Any advice would be fantastic,

Dave.B

**Comment by Chanachon** [comment]
Windows8 have the same problem 
Error occurred while packaging the application:


aapt tool failed:C:\Users\Chanachon\AppData\Local\Temp\862a2a84-d84e-4363-a346-9ce42411f922\res\layout\com_facebook_usersettingsfragment.xml:48: error: Error: No resource found that matches the given name (at 'style' with value '@style/com_facebook_loginview_silver_style').
