### ISSUE TITLE
My App Crashed when recieving GCM Message

### ISSUE THREAD

**Issue by yjb94** [freshplanet/ANE-Push-Notification#32]
hi guys..

I sent GCM message from my server, and it makes my application crash right after I sent it.
I think there is no wrong with my server code, Think sth is wrong with my manifest. can someone give me an answer?

my manifest looks like this

<android>
        <colorDepth>16bit</colorDepth>
        <manifestAdditions>
                <![CDATA[

```
            <manifest>
                <uses-permission android:name="android.permission.INTERNET"/>
                <uses-permission android:name="android.permission.WAKE_LOCK"/>
                <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
                <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
                <uses-permission android:name="android.permission.GET_ACCOUNTS" />
                <uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
                <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

                <permission android:name="air.kr.elever.appElever.debug.permission.C2D_MESSAGE" android:protectionLevel="signature" />
                <uses-permission android:name="air.kr.elever.appElever.debug.permission.C2D_MESSAGE" />




                <application> 

                    <receiver android:name="com.freshplanet.nativeExtensions.C2DMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">

                        <intent-filter>
                            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                            <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

                            <category android:name="air.kr.elever.appElever.debug" />

                        </intent-filter>

                    </receiver>

                    <activity android:name="com.freshplanet.nativeExtensions.NotificationActivity"></activity> 

                    <service android:name="com.freshplanet.nativeExtensions.LocalNotificationService"/>

                    <receiver android:name="com.freshplanet.nativeExtensions.LocalBroadcastReceiver" android:process=":remote"></receiver>

                </application>
        </manifest>
    ]]></manifestAdditions>
  </android>
```

**Comment by pascomach00** [comment]
I think I managed to fix it. It works for my app.
Let me know.
https://drive.google.com/folderview?id=0B6nEmghkuTbZMWc4VGw5alp5Zms&usp=sharing

**Comment by DamboRam** [comment]
Hey @pascomach00 i have download your ane. When i run debug mode a popup is show with below problem :
Problem occured
Error occurred while packaging the application:

dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:123)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:143)
	at com.android.dx.command.dexer.Main.processClass(Main.java:301)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:278)
	at com.android.dx.command.dexer.Main.access$100(Main.java:56)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:130)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:108)
	at com.android.dx.command.dexer.Main.processOne(Main.java:247)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:183)
	at com.android.dx.command.dexer.Main.run(Main.java:139)
	at com.android.dx.command.dexer.Main.main(Main.java:120)
	at com.android.dx.command.Main.main(Main.java:89)
1 error; aborting

**Comment by pascomach00** [comment]
This problem may be because you have another ANE that also tries to import the same library (probably android-support-v4.jar). Can you write a list of all the anes you are using or check for yourself their content (i use winrar to open anes)?

**Comment by DamboRam** [comment]
True i'm using freshplanet AirFacebook.ane does not contain android-support-v4.jar, instead your ane contain android-support-v4.jar so i have removed android-support-v4.jar from your ane and the app run .
But when sending the push notification the app received the below message in the log and crashed:
[StatusEvent type="status" bubbles=false cancelable=false eventPhase=2 code="LOGGING" level="Received push notification with parameters: {"tickerText ":"asdf @ asdfasdf","contentText ":"asdf @ asdfasdf","collapse_key":"do_not_collapse","from":"570916618362","contentTitle ":"PromoScope"}"] Received push notification with parameters: {"tickerText ":"asdf @ asdfasdf","contentText ":"asdf @ asdfasdf","collapse_key":"do_not_collapse","from":"570916618362","contentTitle ":"PromoScope"}

Any idea why the app is crashing ?
i'm using your ane + flex sdk 4.13 with air15.0 and find below my-app.xml:

<permission android:name="air.MY-APP-ID.permission.C2D_MESSAGE" android:protectionLevel="signature" />
<uses-permission android:name="air.MY-APP-ID.permission.C2D_MESSAGE" />
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
<activity android:name="com.freshplanet.nativeExtensions.NotificationActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
			
<receiver android:name="com.freshplanet.nativeExtensions.C2DMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">

<intent-filter>
<action android:name="com.google.android.c2dm.intent.RECEIVE" />
<category android:name="air.MY-APP-ID" />
</intent-filter>

<intent-filter>
<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
<category android:name="air.MY-APP-ID" />
</intent-filter>
</receiver>

<service android:name="com.freshplanet.nativeExtensions.LocalNotificationService"/>
<receiver android:name="com.freshplanet.nativeExtensions.LocalBroadcastReceiver" android:process=":remote"></receiver>

**Comment by AmirSmarty** [comment]
A Fix for firebase?
