### ISSUE TITLE
How to setup icon for LocalPushNotification?

### ISSUE THREAD

**Issue by surajDico** [freshplanet/ANE-Push-Notification#37]
I used below function to send LocalPushNotification but i have no idea about setting up the icon for the same. right now the notification works but  I can only see the title and half the height of the message.

public function local(msg:String, sec:int, title:String):void{
        if(PushNotification.getInstance().isPushNotificationSupported){
            push.sendLocalNotification(msg, (((sec \*  1000) + new Date().getTime())/1000), title);
        }
    }

Please if anyone can help with setting up the icon.

**Comment by pascomach00** [comment]
Don't change the file or folder structure. Just replace the 4 images with your ones
