### ISSUE TITLE
Get payload/message from notification

### ISSUE THREAD

**Issue by varadig** [freshplanet/ANE-Push-Notification#56]
Hi,

How can I get/ what kind of event I get the message or payload from the notification, when the app is on the background, and the user tap the notification to ACTIVATE the application?
I read the PushNotificationEvent API, and tried the APP_STARTING_FROM_NOTIFICATION_EVENT, but the event is not triggered.

thanks

**Comment by Provlax** [comment]
Hi. In your manifest,

change:
<activity android:name="com.freshplanet.nativeExtensions.NotificationActivity" /> 

to:
<activity android:exported="true" android:name="com.freshplanet.nativeExtensions.NotificationActivity"/>

It's worked for me.
