### ISSUE TITLE
Push Notification in Android While App Closed

### ISSUE THREAD

**Issue by pjh00** [freshplanet/ANE-Push-Notification#58]
Help me.......

Project Status

mobile : Andriod Galaxy s4
apk deployment : production(X), Beta(O), Alpa(O), 

Question?

When app is running, it gets the “Push Notification” and shows the messages.
But while app is off, or terminated, there is no answer from Mobile, even though I send messages.
Please let me know if there is something I missed,
or is it just Push Ane system working this way? When App is offline, it doesn’t get any Push Notification?

Thanks

**Comment by leossmith** [comment]
i would also love to know if there is an option to push notifications while the app is closed. thanks
