### ISSUE TITLE
Missing android.support.v4

### ISSUE THREAD

**Issue by CarlitoLoco** [freshplanet/ANE-Push-Notification#61]
Hi,

I've been struggling for a while now trying to get this extension to work.
It all comes down to a problem due to a missing library in the ANE (whatever the version):

Could not find class 'android.support.v4.app.NotificationCompat$Builder', referenced from method com.freshplanet.nativeExtensions.CreateNotificationTask.onPostExecute

The solution (described by smart contributers) is to tweak the build.xml and recompile the ANE.

For all those of us who don't know how to recompile this ANE (setting up a working environment to compile it is a pain), could you post a new revision of the extension including that library?

Thank you for sharing this great ANE with all of us. It's just a small step away from being perfect!

**Comment by rgerlach** [comment]
Hello, I receive the same issue with the latest version (downloaded a few minutes ago):

E/dalvikvm(2542): Could not find class 'android.support.v4.app.NotificationCompat$Builder', referenced from method com.freshplanet.nativeExtensions.CreateNotificationTask.onPostExecute
W/dalvikvm(2542): VFY: unable to resolve new-instance 221 (Landroid/support/v4/app/NotificationCompat$Builder;) in Lcom/freshplanet/nativeExtensions/CreateNotificationTask;
I/PowerManagerService(562): setBrightness mButtonLight 0.
W/dalvikvm(2542): threadid=1: thread exiting with uncaught exception (group=0x40fee9a8)
E/AndroidRuntime(2542): FATAL EXCEPTION: main
E/AndroidRuntime(2542): java.lang.NoClassDefFoundError: android.support.v4.app.NotificationCompat$Builder
E/AndroidRuntime(2542): at com.freshplanet.nativeExtensions.CreateNotificationTask.onPostExecute(Unknown Source)
E/AndroidRuntime(2542): at com.freshplanet.nativeExtensions.CreateNotificationTask.onPostExecute(Unknown Source)
E/AndroidRuntime(2542): at android.os.AsyncTask.finish(AsyncTask.java:631)
E/AndroidRuntime(2542): at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime(2542): at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
E/AndroidRuntime(2542): at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(2542): at android.os.Looper.loop(Looper.java:153)
E/AndroidRuntime(2542): at android.app.ActivityThread.main(ActivityThread.java:5299)
E/AndroidRuntime(2542): at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(2542): at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(2542): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
E/AndroidRuntime(2542): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
E/AndroidRuntime(2542): at dalvik.system.NativeStart.main(Native Method)


I did not recompile the ane, just took the one from the bin folder, renamed, replaced icons in the zip and compiled with updated app descriptor.

**Comment by CarlitoLoco** [comment]
Hi there,

Are there any plans to fix this issue?
Blank project still gives this "Could not find class 'android.support.v4.app.NotificationCompat$Builder' " error, unless the Facebook ANE is also included.

I'm not the only one who has this error and it's a really ugly fix to have to include another ANE to get this working like it should.

I'm aware it is a free ANE and I really appreciate your work and open-mindness to give this to us ignorant folks, but I would really appreciate a fix.

Thanks!

**Comment by s2hago** [comment]
Hi thaks for your build is really helpfull but i get the same "Could not find class 'android.support.v4.app.NotificationCompat$Builder' " please update this we really appreciate

**Comment by pascomach00** [comment]
I think I managed to fix it. It works for my app.
Let me know.
https://drive.google.com/folderview?id=0B6nEmghkuTbZMWc4VGw5alp5Zms&usp=sharing

**Comment by s2hago** [comment]
Hey thank you so much it works!!!!

**Comment by pascomach00** [comment]
You're welcome

**Comment by s2hago** [comment]
Sorry but now I have a problem changing icons... How can I do that? the easy way please I have no idea compiling anes

**Comment by pascomach00** [comment]
open the ane with winrar or something like it and replace the 4 images in AirPushNotification.ane\META-INF\ANE\Android-ARM\res with your ones but keep the same name.
If you alter the structure (add or remove folders or the images have other names) it may not compile.

**Comment by s2hago** [comment]
I already tried that but don't work I changed the extension to zip extract the folders change the icons then add to a rar file  change to ane and nothing please any help will be appreciated

**Comment by pascomach00** [comment]
don't change the extension and don't extract. create your images with the same names in a folder somewhere, open the archive (i use winrar to open ane archives), go to the res folder and drag and drop the new images in that folder (which will replace the old ones with yours).
Good luck!

**Comment by s2hago** [comment]
ok now it works!! thanks man really helpfull

**Comment by roby65** [comment]
How did you fix this issue? I need to recompile it from source as i modified the iOS source code!

**Comment by pascomach00** [comment]
I added platform.xml and the android-support-v4.jar in the Android-ARM folder

**Comment by LucaIaco** [comment]
@pascomach00 I tried your method, but still seems to return me the *Could not find class 'android.support.v4.app.NotificationCompat$Builder*. I'm using the Adobe Flash CC 2014, and when the apk is built, i tried to decompile that, so i discovered that all the source exist ( like com/something/else, com/google/android/gms/..... ) BUT not the android/support/v4/.... . Instead, seems that the build apk contains only the android/support/v7/appcompat/R.java ( .java because is decompiled ). In the .ane file i have the android-support.v4.jar, and also the contained platform.xml at /META-INF/ANE/Android-ARM/.
In the eclipse project i tried to include the support-v4 library in all the possible ways, like dependency project, external jar, or kept as defult library in the libs folder. I can't figure out how to fix it....

**Comment by pascomach00** [comment]
download and try mine
https://drive.google.com/folderview?id=0B6nEmghkuTbZMWc4VGw5alp5Zms&usp=sharing

**Comment by LucaIaco** [comment]
Tried now, and seems that your ane file is 'accepted' somehow, i mean, including your ane, and then, decompiling the resulting apk, i see the android/support/v4... i really don't understand what is my problem, maybe the android.support.v4.jar version?

**Comment by LucaIaco** [comment]
@pascomach00 

It really crazy..... It was the version of android.support.v4.jar. I made a test now, for some magic reason, using the one i had before (i got it, in Eclipse, with right click on the library project, Android Tools > Add Support Library ). i used the android.support.v4.jar included in your ane file, and i test also with a version of another ane project, and this solved the problem! Just to say, using the Add Support Library method, the android.support.v4 file size was 1.2 MB, yours is 759KB, and the other one i tested was 628KB, depending on their version. I was expecting that this library was properly added by eclipse, also relying on the androd target in the project.properties, but seems not. Hope this could help someone

**Comment by RobertNelson** [comment]
Just worked through a similar issue. Are you including `AndroidSupport.ane` in your project? We weren't.
