### ISSUE TITLE
Ios8 iphone 6

### ISSUE THREAD

**Issue by ate864** [freshplanet/ANE-Push-Notification#64]
Hi

Every thing work fine on ios7 (iphone 4)s and Android but i test notification on iphone 6 with ios8 and no push token id is return to the phone...
No error just nothing happen...

Thank you for your help

**Comment by enpela** [comment]
Similarly, I also iPadmini of iOS8, device token can not be acquired.
May be ...
I expect that because I changed the methods necessary to push notification in iOS8

-application: didRegisterUserNotificationSettings
And
-registerForRemoteNotifications
And so

I am waiting for a response.

Thank you.

**Comment by pauloamorimbr** [comment]
Any news on this? 

I cannot make push notifications for iOS to work with the "native Air support" (because it just doesn't work), and I'm not able to make this ANE work (thanks to freshplanet, tho, for the awesome ANEs)...the popup asking the user for permission never shows, I never receive a token back.

Please? Any update? Any help?

**Comment by YeeshaYe** [comment]
http://stackoverflow.com/questions/25909568/ios-8-enabled-device-not-receiving-push-notifications-after-code-update

I think this is a solution for how to edit extension... waiting for .ane update.

**Comment by pauloamorimbr** [comment]
No updates, I guess? :(

**Comment by zing1911** [comment]
I got something wrong with this code (PushNotification.as) . I'm not sure that is cause of token return null 

I have debug this Lib (PushNotification) and I got something wrong on this line 

.....
extCtx = ExtensionContext.createExtensionContext("com.freshplanet.AirPushNotification", null);
(1) (That result is null)				
					if (extCtx != null)
					{
						extCtx.addEventListener(StatusEvent.STATUS, onStatus);
					} else <------ (2) go to else
					{
						trace('extCtx is null.'); <---- trace something that's invisible
					}
_instance = this; <---- (3) set it 
......

if I have anything got work, I will update as soon as possible
