### ISSUE TITLE
air_sdk_16.0.0.292 required to have universal iOS libraries

### ISSUE THREAD

**Issue by jpjob** [freshplanet/ANE-Push-Notification#66]
Hello. I compile the project and flash builder say error

Error occurred while packaging the application:

Error: META-INF/ANE/iPhone-ARM/libproductStore.a, META-INF/ANE/iPhone-ARM/libVibrationiOSLibrary.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.

if i rebuild by ANT(i set in XCODE Standart archeticture and VALID ARCH arm64 armv7 armv7s)

package:
     [exec] Error: Apple App Store allows only universal applications. "libAirPushNotification.a" is not a universal binary. Please change build settings in Xcode project to "Standard Architecture" to create universal library/framework.

please help me. Thanx

UPDATE:
And local push notification not working on ipod with IOS 8.1.3
On iphone 6 with IOS 8.1.3 work fine

**Comment by zing1911** [comment]
I solve this problem by this link : 

http://easynativeextensions.com/making-your-ios-apps-universal/
