### ISSUE TITLE
[ANDROID] Crash application on receive the push notification

### ISSUE THREAD

**Issue by antiheroi** [freshplanet/ANE-Push-Notification#74]
Apple is working perfectly, but on Android the ANE is working properly ultil receive any notification as in background as foreground. Says that application is not responding, if click "OK" close the application, if I click for wait, the application keep freezing.

**Comment by mariommoreno** [comment]
I had a similar problem and I found that the Android notification part of this ANE expects an specific JSON formated data, did you tried this?

data = {"contentTitle":"TITLE HERE", "contentText":"Content text here!", "tickerText":"extra text"}

**Comment by markelmad** [comment]
Anyone manage to fix this? I am using App42Cloud and I can't manage to explicitly send a custom JSON data so app crashing persists.

Thanks in advance!

**Comment by esdebon** [comment]
then recompile it

2015-06-04 19:15 GMT-05:00 markelmad <notifications@github.com>:

> Anyone manage to fix this? I am using App42Cloud and I can't manage to
> explicitly send a custom JSON data so app crashing persists.
>
> Thanks in advance!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freshplanet/ANE-Push-Notification/issues/74#issuecomment-109101160>
> .
>



-- 
*Saludos*

*J. Emmanuel G. M*.

**Comment by suitable-hero** [comment]
Same here, Android 4 and 5 not working :/ There have been some changes to this branch 18 hours ago, but is the Android issue fixed?

The GCM ane described here seems to work: 
https://www.as3gamegears.com/air-native-extension/android-gcm/

I tested it on Android 4.x and the notifications work great, but no vibration or sound :(

Also, is it possible for a push notification to wake locked Android screen in Adobe Air app?
