### ISSUE TITLE
Opening specific page inside app on pressing Push Notification(adobe air) android

### ISSUE THREAD

**Issue by surajDico** [freshplanet/ANE-Push-Notification#75]
Anyone ever tried opening specific page inside app on tapping the push notification. I am working on adobe air flash and is an android app.

**Comment by afarber** [comment]
What code have you tried sofar?

**Comment by surajDico** [comment]
Right now i am just using freshplanet push notification to send server side PNS. i haven't tried anything to open a specific page inside app. i am searching for some reference.

**Comment by afarber** [comment]
Then your question is not related to the Freshplanet ANE.
